### PR TITLE
Feat: Created Linkedin field

### PR DESCRIPTION
**Pull request by by-bai**
# Notion Task

https://www.notion.so/Create-Linkedin-field-f9ccd2e448e3414d863d14a51ce39926

# Changes Made In This PR

- Added Linkedin field
- Added Linkedin info to Contact blocks to be displayed on the resume

# Screenshots
Screenshot 2022-01-12 at 10 14 52 PM

### CODE REVIEW

**Review by millasml — CHANGES_REQUESTED** [review]
you need to update Resume.ts, initialState and demoState too to include the linkedin field

**Comment by millasml** [comment]
i realized that keerthi kinda did this already: https://github.com/CareerSocius/resumebuilder/pull/64

**Comment by by-bai** [comment]
> scratch that, i realized that keerthi kinda did this already in: #64
> 
> please wait for that PR to merge, then rebase this!

okay!!

**Comment by millasml** [comment]
@by-bai the PR has been merged! please rebase this so we can merge it in too :D

**Review by millasml — APPROVED** [review]

**Pull request merged**
