### PR TITLE
Feat: Added volunteer section & Updated project fields

### PR DESCRIPTION
**Pull request by by-bai**
# Notion Task

https://www.notion.so/Creation-of-volunteer-work-section-42e738961cc64a988c59c4cca08552a4

# Changes Made In This PR

- Added `Volunteer.js` and `VolunteerModal.js`
- Added Volunteer section to left sidebar with new icon
- Added `VolunteerA.js` block for demo purposes on the 'Onyx' demo template
- Updated `demoState.ts` and `initialState.ts` to include both Projects and Volunteer

# Also In This PR

- Updated fields in `Project` section according to Figma

# Screenshots

## Before 

_Initial State_
Screenshot 2022-01-13 at 11 24 42 PM

Screenshot 2022-01-13 at 11 26 53 PM

_After clicking on "Load Demo Data", the heading of 'Projects' section changes to 'Volunteer' section_
Screenshot 2022-01-13 at 11 25 45 PM

_and renders as Volunteer on the resume template_
Screenshot 2022-01-13 at 11 25 16 PM

## After

_Projects and Volunteer sections are separate in both initial & demo state_
Screenshot 2022-01-13 at 11 22 24 PM

Screenshot 2022-01-13 at 11 22 43 PM

Screenshot 2022-01-13 at 11 22 55 PM

Screenshot 2022-01-13 at 11 21 50 PM

### CODE REVIEW

**Review by millasml — CHANGES_REQUESTED** [review]
looks really good! just a few additional things:

- for the project fields, can you make it such that start date and end date are on the same line, and then website is on a line of its own?
- right now even though you collect the project dates, the dates will never get rendered in the template. Can you discuss with raei and add "Make templates show Project dates" as a task to one of the epics?
- you dont have to do it with this PR, but can you do this task to add [volunteer work tooltips](https://www.notion.so/70204328dfbc4abfa76a39d9c3b50169?v=21f1019a9ecd49b791569d2ce69e5cc7&p=baaffe3cab274f018340cfc1bc491907) too?

**Comment by by-bai** [comment]
> * for the project fields, can you make it such that start date and end date are on the same line, and then website is on a line of its own?

done!

**Screenshot:**
Screenshot 2022-01-14 at 10 36 00 PM

> * right now even though you collect the project dates, the dates will never get rendered in the template. Can you discuss with raei and add "Make templates show Project dates" as a task to one of the epics?
> * you dont have to do it with this PR, but can you do this task to add [volunteer work tooltips](https://www.notion.so/70204328dfbc4abfa76a39d9c3b50169?v=21f1019a9ecd49b791569d2ce69e5cc7&p=baaffe3cab274f018340cfc1bc491907) too?

okie will do!

**Review by millasml — APPROVED** [review]
looks good but seems like it needs a rebase because I merged your other one first :( @by-bai

**Comment by by-bai** [comment]
Updates: added startDate & endDate fields as requested by Raei!

**Review by tharshita — APPROVED** [review]

**Pull request merged**
