### PR TITLE
Feat: Added drop down for sections

### PR DESCRIPTION
**Pull request by by-bai**
# Notion Task

https://www.notion.so/Drop-down-for-each-section-d92a38b33c484515826689bd30ce8d75

# Changes Made In This PR

- Added accordions (https://v4.mui.com/components/accordion/) for dropdown
- Shifted `Heading` from `Profile.js` to `Content.js`

# Also In This PR
- Changed 'Volunteer' field to 'Projects' in `HeadingI.js` to fix Timeline bug in Zety Data Analyst template
- Changed 'Professional Experience' to 'Work Experience' in `demoState.ts`

# Screenshots

**Before:**
Screenshot 2022-01-24 at 12 20 46 AM

**After:**
Screenshot 2022-01-24 at 8 03 28 PM

### CODE REVIEW

**Review by millasml — APPROVED** [review]
this looks good so far, so i'm going to approve it and let it merge in first. 

However, eventually, can you make it such that the big header is in the AccordionSummary, and not in the AccordionDetails? I know this is going to be a big change as you have to move the heading as well as the tooltips up. We can discuss the best way to do this later!
image

**Comment by by-bai** [comment]
Okay!

**Review by millasml — CHANGES_REQUESTED** [review]
looks good, but can you hide the scrollbars? there should only be one scroll bar for the panel

**Comment by kvihashini** [comment]
> looks good, but can you hide the scrollbars? there should only be one scroll bar for the panel

oh right! okay, will fix it :-)

**Pull request merged**
